trigger: none  # Manual trigger only

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Kubernetes@1
  displayName: 'Test cluster connection'
  inputs:
    connectionType: 'Azure Resource Manager' # or 'Kubeconfig' if your service connection uses kubeconfig
    kubernetesServiceEndpoint: 'MediaK8sJioGateNonProd1.25'
    namespace: 'default'
    command: 'get'
    arguments: 'nodes'
