trigger: none  # Ensures pipeline does NOT run automatically

pool:
  vmImage: 'ubuntu-latest'

variables:
  KUBECONFIG_PATH: '$(Build.ArtifactStagingDirectory)/kubeconfig'

steps:
# Step 1: Install kubectl if not present
- task: KubernetesInstaller@0
  inputs:
    kubernetesVersion: 'latest'

# Step 2: Configure kubeconfig using your service connection
- task: Kubernetes@1
  displayName: 'Set kubeconfig from service connection'
  inputs:
    connectionType: 'Azure Resource Manager' # or 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'MediaK8sJioGateNonProd1.25'
    command: 'config'
    secretType: 'None'
    kubeconfig: '$(KUBECONFIG_PATH)'

# Step 3: Verify cluster connection (read-only)
- script: |
    echo "Checking cluster info..."
    kubectl cluster-info
    echo "Listing nodes..."
    kubectl get nodes
  displayName: 'Test cluster connection'

# Step 4: Publish kubeconfig as an artifact
- publish: $(Build.ArtifactStagingDirectory)/kubeconfig
  artifact: kubeconfig
  displayName: 'Publish kubeconfig'
