trigger: none  # so it doesn't run automatically

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Kubectl@1
  inputs:
    kubernetesServiceConnection: 'MediaK8sJioGateNonProd1.25'
    command: 'config view'
    arguments: '--flatten'
