trigger: none  # Manual run only

pool:
  vmImage: 'ubuntu-latest'

steps:

# Step 1: Download kubeconfig from service connection
- task: Kubectl@1
  displayName: 'Download kubeconfig'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'MediaK8sJioGateNonProd1.25'
    command: 'version' # Just ensures the kubeconfig works
  continueOnError: true

# Step 2: Test cluster connectivity (read-only)
- task: Kubectl@1
  displayName: 'Test cluster nodes'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'MediaK8sJioGateNonProd1.25'
    command: 'get'
    arguments: 'nodes'
