trigger: none  # manual run only

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Kubectl@1
  displayName: 'Test cluster connection'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'MediaK8sJioGateNonProd1.25'
    command: 'get'
    arguments: 'nodes'
