trigger: none  # Prevent automatic runs

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Install kubectl (if not already available on agent)
- task: UseKubectl@1
  inputs:
    version: 'latest'

# Step 2: Verify cluster connectivity
- script: |
    echo "Checking cluster info..."
    kubectl cluster-info
    echo "Listing nodes..."
    kubectl get nodes
  displayName: 'Check Kubernetes cluster'

# Step 3: Optional: Print current context
- script: |
    echo "Current kubectl context:"
    kubectl config current-context
  displayName: 'Show current context'
